version: "3.7"

services:
    webapp:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        working_dir: /var/www/html
        container_name: laravel_php
        restart: always
        environment:
            DB_HOST: db
            DB_USER: laravel
            DB_PASSWORD: secret
            DB_NAME: laravel
        ports:
            - 8000:80
            - 5173:5173
        volumes:
            - ./laravel:/var/www/html
        depends_on:
            - db
        networks:
            - laravel_network

    db:
        image: mysql:8.0.34
        container_name: laravel_db
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - ./mysql_data:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - laravel_network

networks:
    laravel_network:
        driver: bridge

volumes:
  mysql_data: